'use strict';

module.exports = {
    app: 'src/main/webapp/',
    version:'1.0.0',
    dist: 'dist/',
    bower: 'src/main/webapp/bower_components/',
    tmp: 'dist/tmp',
    revManifest: 'dist/tmp/rev-manifest.json',
    port: 9000,
    apiPort: 8080,
    liveReloadPort: 35729,
    uri: 'http://localhost:',
    constantTemplate:
        '(function () {\n' +
        '   \'use strict\';\n' +
        '   // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
        '   angular\n' +
        '       .module(\'<%- moduleName %>\')\n' +
        '       .constant(\'APP_CONSTANT\',{\n'+
        '<% constants.forEach(function(constant) { %>           \'<%= constant.name %>\': <%= constant.value %>,\n<% }) %>\n' +
        '       })\n' +
        '})();\n'
};
